Repository PowerLevel9000/Awesome-Books, pull requests merged in 2023-01, with the labels that each got.

#1 Devlopment
  .eslintrc.json
  .github/workflows/linters.yml
  .gitignore
  .hintrc
  .stylelintrc.json
  README.md
  index.html
  media/Awesome-book-initial.png
  media/dilsher-favicon/android-chrome-192x192.png
  media/dilsher-favicon/android-chrome-512x512.png
  media/dilsher-favicon/apple-touch-icon.png
  media/dilsher-favicon/favicon-16x16.png
  media/dilsher-favicon/favicon-32x32.png
  media/dilsher-favicon/favicon.ico
  media/dilsher-logo.png
  media/my-logo.png
  package-lock.json
  package.json
  script.js
  style.css
  upcommingEvents/fire.webp
  upcommingEvents/images.jpg
Labels: bug, enhancement, help wanted, question

#2 Added styling initial And using js Classes
  README.md
  index.html
  media/Awesome-book-initial.png
  script.js
  style.css
Labels: documentation, enhancement, question

#4 Date with luxon module
  README.md
  dist/index.html
  src/date.js
  src/luxon.js
  src/script.js
  style.css
Labels: documentation
